on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  integration-test:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.6

      - name: Set BOOTSTRAP_PIP_SPEC value
        run: |
          echo "BOOTSTRAP_PIP_SPEC=git+https://github.com/$GITHUB_REPOSITORY.git@$GITHUB_REF" >> $GITHUB_ENV

      - name: Build systemd image
        run: |
          .github/integration-test.py build-image

      - name: Run bootstrap checks
        run: |
          python3 -m pip install pytest
          pytest --verbose --maxfail=2 --color=yes --capture=no integration-tests/test_bootstrap.py

      - name: Run basic tests
        run: |
          .github/integration-test.py run-test \
            --bootstrap-pip-spec "$BOOTSTRAP_PIP_SPEC" \
            basic-tests test_hub.py test_proxy.py \
            test_install.py test_extensions.py

      - name: Run admin tests
        run: |
          .github/integration-test.py run-test \
            --installer-args "--admin admin:admin" \
            --bootstrap-pip-spec "$BOOTSTRAP_PIP_SPEC" \
            basic-tests test_admin_installer.py

      - name: Run plugin tests
        run: |
          .github/integration-test.py run-test \
            --bootstrap-pip-spec "$BOOTSTRAP_PIP_SPEC" \
            --installer-args "--plugin /srv/src/integration-tests/plugins/simplest" \
            plugins test_simplest_plugin.py
