on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  upgrade-test:
    if: ${{ github.ref != 'refs/heads/master' }}
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - name: Set BOOTSTRAP_PIP_SPEC value
        run: |
          echo "BOOTSTRAP_PIP_SPEC=git+https://github.com/$GITHUB_REPOSITORY.git@$GITHUB_REF" >> $GITHUB_ENV
          echo $BOOTSTRAP_PIP_SPEC
      - name: Build systemd image
        run: |
          .github/integration-test.py build-image
      - name: Run basic tests
        run: |
          .github/integration-test.py run-test \
            --bootstrap-pip-spec "$BOOTSTRAP_PIP_SPEC" \
            basic-tests test_hub.py test_proxy.py \
            test_install.py test_extensions.py \
            --upgrade
      - name: Run admin tests
        run: |
          .github/integration-test.py run-test \
            --installer-args "--admin admin:admin" \
            --bootstrap-pip-spec "$BOOTSTRAP_PIP_SPEC" \
            basic-tests test_admin_installer.py \
            --upgrade
      - name: Run plugin tests
        run: |
          .github/integration-test.py run-test \
            --bootstrap-pip-spec "$BOOTSTRAP_PIP_SPEC" \
            --installer-args "--plugin /srv/src/integration-tests/plugins/simplest" \
            plugins test_simplest_plugin.py \
            --upgrade
